#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class SucceededJobs : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
  
    Layout = new LayoutPage(Strings.SucceededJobsPage_Title);

    int from, perPage;
    string title = Query("name");
    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    var monitor = Storage.GetMonitoringApi();
    var pager = new Pager(from, perPage, monitor.SucceededListCount());
    var succeededJobs = monitor.SucceededJobs(pager.FromRecord, pager.RecordsPerPage, title);


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <script type=\"text/javascript\">\r\n        var baseUrl = \"" +
"");


            
            #line 22 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                  Write(Url.To("/jobs/succeeded"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        var name = \"");


            
            #line 23 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
               Write(Query("name"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n    </script>\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 26 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">");


            
            #line 29 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                           Write(Strings.SucceededJobsPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 31 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
         if (pager.TotalPageCount == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-info\">\r\n                ");


            
            #line 34 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
           Write(Strings.SucceededJobsPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 36 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"js-jobs-list\">\r\n                <div class=\"btn-toolbar b" +
"tn-toolbar-top\">\r\n                    <button class=\"js-jobs-list-command btn bt" +
"n-sm btn-primary\"\r\n                            data-url=\"");


            
            #line 42 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                 Write(Url.To("/jobs/succeeded/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            data-loading-text=\"");


            
            #line 43 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                          Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            disabled=\"disabled\">\r\n                        <spa" +
"n class=\"glyphicon glyphicon-repeat\"></span>\r\n                        ");


            
            #line 46 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                   Write(Strings.Common_RequeueJobs);

            
            #line default
            #line hidden
WriteLiteral(@"
                    </button>
                    <input type=""text"" id=""title"" class=""input-medium search-query"" style=""display: inline-block; padding: 4px 6px; font-size: 14px; line-height: 20px; color: #555555; vertical-align: middle; margin-left: 10px; width: 300px;"" placeholder=""输入名称.."" value=""");


            
            #line 48 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                                                                                                                                                                                                                                                         Write(Query("name"));

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                    <button type=\"button\" class=\"btn\" style=\"float: inherit;" +
"\" id=\"search\">查询</button>\r\n                    ");


            
            #line 50 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
               Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral(@"
                </div>

                <div class=""table-responsive"">
                    <table class=""table"">
                        <thead>
                        <tr>
                            <th class=""min-width"">
                                <input type=""checkbox"" class=""js-jobs-list-select-all""/>
                            </th>
                            <th class=""min-width"">");


            
            #line 60 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                             Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>作业名称</th>\r\n                            <th" +
" class=\"min-width\">执行时间</th>\r\n                            <th class=\"align-right" +
"\">");


            
            #line 63 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                               Write(Strings.SucceededJobsPage_Table_Succeeded);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        </tr>\r\n                        </thead>\r\n         " +
"               <tbody>\r\n");


            
            #line 67 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                         foreach (var job in succeededJobs)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr class=\"js-jobs-list-row ");


            
            #line 69 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                                    Write(job.Value == null || !job.Value.InSucceededState ? "obsolete-data" : null);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 69 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                                                                                                                 Write(job.Value != null && job.Value.InSucceededState ? "hover" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                <td>\r\n");


            
            #line 71 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                     if (job.Value == null || job.Value.InSucceededState)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input type=\"checkbox\" class=\"js-jobs-lis" +
"t-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 73 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                                                                                             Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n");


            
            #line 74 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n                                <td class=" +
"\"min-width\">\r\n                                    ");


            
            #line 77 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                               Write(Html.JobIdLink(job.Key));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 78 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                     if (job.Value != null && !job.Value.InSucceededState)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <span title=\"");


            
            #line 80 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                                Write(Strings.Common_JobStateChanged_Text);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"glyphicon glyphicon-question-sign\"></span>\r\n");


            
            #line 81 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n\r\n");


            
            #line 84 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                 if (job.Value == null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <td colspan=\"3\">\r\n                           " +
"             <em>");


            
            #line 87 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                       Write(Strings.Common_JobExpired);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n                                    </td>\r\n");


            
            #line 89 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <td class=\"word-break\">\r\n                    " +
"                    ");


            
            #line 93 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                   Write(Html.JobNameLink(job.Key, job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n");



WriteLiteral("                                    <td class=\"min-width align-right\">\r\n");


            
            #line 96 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                         if (job.Value.TotalDuration.HasValue)
                                        {
                                            
            
            #line default
            #line hidden
            
            #line 98 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                       Write(Html.ToHumanDuration(TimeSpan.FromMilliseconds(job.Value.TotalDuration.Value), false));

            
            #line default
            #line hidden
            
            #line 98 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                                                                                                                  
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n");



WriteLiteral("                                    <td class=\"min-width align-right\">\r\n");


            
            #line 102 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                         if (job.Value.SucceededAt.HasValue)
                                        {
                                            
            
            #line default
            #line hidden
            
            #line 104 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                       Write(Html.RelativeTime(job.Value.SucceededAt.Value));

            
            #line default
            #line hidden
            
            #line 104 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                                                                           
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n");


            
            #line 107 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tr>\r\n");


            
            #line 109 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n                <" +
"/div>\r\n\r\n                ");


            
            #line 114 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
           Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 116 "..\..\Dashboard\Pages\SucceededJobs.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
